name: AutoGen coder
on:
  issues:
    types: [labeled]

jobs:
  code:
    if: github.event.label.name == 'now-working'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install -r requirements.txt
      - run: python autogen_project/main.py  # CoderAgent 실행
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN:   ${{ secrets.GITHUB_TOKEN }}